version: "3.3"
services:
  redis-server:
      image: redis
      container_name: redis
      ports: 
        - "6379:6379"
      volumes: 
        - ./redis-service/config/redis.conf:/redis.conf
        # - ./redis-data:/redis.conf
      command: [ "redis-server", "/redis.conf" ]
      networks: 
        - backend-network

  api-gateway:
    container_name: api-gateway
    build:
      args: 
        - NODE_ENV=development
      context: ./api-gateway
    command: node dist/main.js
    ports:
      - 3001:3001
    restart: unless-stopped
    links:
      - redis-server
    depends_on:
      - redis-server
    volumes:
      - type: bind
        source: ./public
        target: /home/node/api/public
        volume:
          nocopy: true
      - /etc/localtime:/etc/localtime:ro
    working_dir: /home/node/api
    networks: 
      - backend-network
  products-service:
    container_name: products-service
    build:
      args: 
        - NODE_ENV=development
      context: ./products
    command: node dist/main.js
    ports:
      - 3002:3002
    restart: unless-stopped
    links:
      - redis-server
    depends_on:
      - redis-server
    volumes:
      - type: bind
        source: ./public
        target: /home/node/api/public
        volume:
          nocopy: true
      - /etc/localtime:/etc/localtime:ro
    working_dir: /home/node/api
    networks: 
      - backend-network
 
networks:
  backend-network:
volumes:
  data_volume: